<template><h1 id="faq" tabindex="-1"><a class="header-anchor" href="#faq" aria-hidden="true">#</a> FAQ</h1>
<h3 id="q-what-is-the-relationship-between-pixltonian-and-rss" tabindex="-1"><a class="header-anchor" href="#q-what-is-the-relationship-between-pixltonian-and-rss" aria-hidden="true">#</a> Q: What is the relationship between Pixltonian and RSS?</h3>
<p>A: The founders of Pixltonian are big fans of RSS, and aspire to the free and open Internet typically represented by RSS in the Web1 era. We made the <a href="https://github.com/DIYgod/RSSHub" target="_blank" rel="noopener noreferrer">RSSHub<ExternalLinkIcon/></a> project based on the RSS protocol in an effort to integrate RSS with Web2 products, but due to the many limitations of the protocol, the project is like dancing with shackles on its feet. We all know that the design of RSS is no longer able to meet the more complex information aggregation and distribution needs of the current Internet. So we create Pixltonian, expecting that the spirit of RSS would be passed on in the Web3 era. In order to meet the complex needs of Web2 and Web3, the design and implementation of Pixltonian is very different from RSS, and they are no other related except for the design concept.</p>
<h3 id="q-what-is-the-relationship-between-pixltonian-and-pixltonian-network" tabindex="-1"><a class="header-anchor" href="#q-what-is-the-relationship-between-pixltonian-and-pixltonian-network" aria-hidden="true">#</a> Q: What is the relationship between Pixltonian and Pixltonian Network?</h3>
<p>A: Pixltonian is also known as Pixltonian Protocol, it defines the format of information presence and communication, and the Pixltonian Network is a decentralized implementation of the Pixltonian Protocol, and provides some additional methods of easily accessing data based on the protocol.</p>
<h3 id="q-why-pixltonian-network-store-data-on-a-distributed-network-instead-of-on-a-blockchain" tabindex="-1"><a class="header-anchor" href="#q-why-pixltonian-network-store-data-on-a-distributed-network-instead-of-on-a-blockchain" aria-hidden="true">#</a> Q: Why Pixltonian Network store data on a distributed network instead of on a blockchain?</h3>
<p>A: We know storing data on the blockchain is a kind of Web3 political correctness, but storing data on a distributed network with signatures as consensus is a kind of technical correctness at this stage. First of all, the exaggerated inefficiency and high cost of blockchain increases the threshold of use, and to some extent hinders information distribution and decentralization, low efficiency makes it impossible to compete with centralized platforms with high efficiency and excellent experience, high cost prevents most developers and users from using it, and many developers and users have to use the centralized platform OpenSea explains this point clearly, secondly blockchain itself cannot perform data indexing, analysis and aggregation, and cannot achieve complex needs such as indexing user dynamics from other platforms and returning all followers of a user easily and quickly. While this may be difficult for some staunch blockchain believers to accept, we believe that our enemy is not other Web3 applications but Web2 centralized platforms, and the richer functionality, greater flexibility and efficiency that a distributed network brings can help us achieve our goals. We are also delighted to see the emergence and widespread acceptance of other distributed networks such as IPFS and Arweave.</p>
<h3 id="q-what-is-the-relationship-between-pixltonian-and-applications-revery-cheers" tabindex="-1"><a class="header-anchor" href="#q-what-is-the-relationship-between-pixltonian-and-applications-revery-cheers" aria-hidden="true">#</a> Q: What is the relationship between Pixltonian and applications Revery Cheers?</h3>
<p>A: Revery and Cheers are demos and early testbeds for the Pixltonian Protocol and Pixltonian Network, they will gradually be turned into a normal eco-project to be maintained by the community.</p>
</template>
